name: CI/CD

env:
  EB_PACKAGE_S3_BUCKET_NAME : "flash-github1"
  DEPLOY_PACKAGE_NAME       : "flask-app-${{ github.sha }}.jar"
  AWS_REGION_NAME           : "us-east-1"
  

on:
  push:
    branches:
      - master

jobs:
  
   my_ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8  
      - name: Build, Test and Publish package (.jar file) to GitHub
        run: mvn -B clean package

      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
             aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}

      - name: Copy our Deployment package to S3 bucket
        run : aws s3 cp /home/runner/work/petclinic-classic-ci-cd-aws/petclinic-classic-ci-cd-aws/target/petclinic.war s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/

      - name: Print nice message on completion of CI Pipeline
        run : echo "CI Pipeline part finished successfully"
   my_cd_pipeline:
       runs-on: ubuntu-latest
       needs: [my_ci_pipeline]
       if: github.ref == 'refs/heads/master'
       steps:
        - name: AWS Create Deploy
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
            aws-secret-access-key  : ${{ secrets.MY_AWS_SECRET_KEY }}
            aws-region             : ${{ env.AWS_REGION_NAME }}
        - name: deployment in instances
          run:
             aws deploy create-deployment
               --application-name sampleapp
               --deployment-config-name CodeDeployDefault.OneAtATime
               --deployment-group-name groupapp
               --file-exists-behavior OVERWRITE
               --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
       
        - name: Print nice message on completion of CD Pipeline
          run : echo "CD Pipeline part finished successfully"  
          
     
